spring.application.name=sahal_portfolio_backend

# =========================
# DATABASE CONFIGURATION
# =========================
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# =========================
# FRONTEND URL
# =========================
frontend.url=${FRONTEND_URL}

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# MAIL CONFIGURATION
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

client.name=Sahal

# SMTP AUTH
spring.mail.properties.mail.smtp.auth=true

# TLS CONFIGURATION
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# DISABLE SSL FOR PORT 587
spring.mail.properties.mail.smtp.ssl.enable=false

# TIMEOUTS
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000