spring.application.name=sahal_portfolio_backend
spring.datasource.url=jdbc:mysql://localhost:3306/sahal_portfolio
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true